spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: localdb
      auto-index-creation: true
  mongodb:
    embedded:
      version: 6.0.11
      enabled: true

# Enable embedded MongoDB for local development
de.flapdoodle.mongodb.embedded.version: 6.0.11
