spring:
  profiles:
    active: local

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,loggers,metrics,refresh,shutdown
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  health:
    show-components: always

# Debug logging for troubleshooting
logging:
  level:
    # Flapdoodle embedded MongoDB debugging
    de.flapdoodle.embed: DEBUG
    de.flapdoodle.embed.mongo: DEBUG
    de.flapdoodle.embed.process: DEBUG
    # Spring Data MongoDB debugging
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.mongodb.core: DEBUG
