spring:
  config:
    activate:
      on-profile: prod
  # MongoDB connection is managed by MongoConfig.java which reads credentials from a file
  # Only need to disable embedded MongoDB in production
  mongodb:
    embedded:
      enabled: false
